/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_TEST_ALL_TYPES_H__
#define __RS_TEST_ALL_TYPES_H__

#include <rs_test/types/type_definitions.h>
#include <rs_test/types/test_types.h>


#endif /* __RS_TEST_ALL_TYPES_H__ */
