/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_TEST_TYPE_DEFINITIONS_H__
#define __RS_TEST_TYPE_DEFINITIONS_H__

#define RS_TEST_TEST_CENTROID "rs_test.test.Centroid"
#define RS_TEST_TEST_EXAMPLEANNOTATION "rs_test.test.ExampleAnnotation"

#endif /* __RS_TEST_TYPE_DEFINITIONS_H__ */
